### PR TITLE
fix issue #142 - multicast group parsing when not configured

### PR DESCRIPTION
**Pull request by mrvinti**
This fixes the issue #142 by excluding the `multicast-group decap` line so the multicast group is '' when not configured.

An additional test has been added for parsing the multicast group when set.

### CODE REVIEW

**Comment by jerearista** [comment]
Thank you for this contribution.   I just saw this the other day, too and was going to fix in commit 2a22503edc7bac0617b9164537823597c46f003f.   Its a slightly different change to the regex.   In this one, we ensure we only search lines that start with '^\s{3}' for this list.  That way its not  tied to any specific group-name, etc.  Do you see any issues with that approach?  If not, please update your PR and we'll bring that in.

**Comment by mrvinti** [comment]
@jerearista I think your solution is cleaner. Maybe one little slight improvement would be not to make it dependent on the whitespace count like this: `/^\s*vxlan multicast-group ([^\s]+)$/`.

What do you think?

**Comment by jerearista** [comment]
I like it. Thanks!

👍

**Comment by mrvinti** [comment]
@jerearista I removed the multicast-set test which was already defined in interfaces_vxlan_spec. should be good now.

**Comment by jerearista** [comment]
Jenkins: test this please

**Comment by jerearista** [comment]
Jenkins, test this please

**Pull request merged**
