### PR TITLE
extend and fix ospf features

### PR DESCRIPTION
**Pull request by rknaus**
* add additional ospf instance settings
 * max_lsa
 * maximum_paths
 * passive_interface_default
 * passive_interfaces
 * active_interfaces
* change return parameters from string to symbol
* fix get interfaces function
* fix set redistribution function

### CODE REVIEW

**Comment by jerearista** [comment]
Jenkins, test this please

**Comment by jerearista** [comment]
We are happy with your approach.  Please run rubocop and ensure there is a testcase for both the single-line as well as the multiline output formats, then we'll get this merged in.

**Comment by rknaus** [comment]
@jerearista did you mean https://github.com/arista-eosplus/rbeapi/pull/155 instead of my pull request?

**Comment by jerearista** [comment]
@rknaus, I want to run this through an additional layer of testing along with the Puppet type/provider and multiple Puppet versions to ensure the desired behavior of the symbols vs strings before merging. It may be a few days before I get back to you on this.  Otherwise, it looks good.

**Pull request merged**
