### PR TITLE
Address code coverage gaps

### PR DESCRIPTION
**Pull request by websitescenes**

### CODE REVIEW

**Comment by websitescenes** [comment]
Addresses issue #66

**Comment by websitescenes** [comment]
Please retest this

**Comment by websitescenes** [comment]
Retest this please.

**Comment by websitescenes** [comment]
Retest this please.

**Comment by websitescenes** [comment]
retest this please

**Comment by websitescenes** [comment]
retest this please

**Comment by websitescenes** [comment]
retest this please

**Comment by websitescenes** [comment]
retest this please

**Comment by websitescenes** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please (reset jenkins host)

**Pull request merged**
