### PR TITLE
Feature puppet4 swix

### PR DESCRIPTION
**Pull request by jerearista**
Fix some rubocop findings, a typo, and add a task to generate SWIX files.

### CODE REVIEW

**Comment by jerearista** [comment]
please retest this

**Comment by jerearista** [comment]
Jenkins testing:   retest this please

**Comment by jerearista** [comment]
Testing
retest this please

**Comment by jerearista** [comment]
testing
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Comment by devrobo** [comment]
retest this please

**Pull request merged**
