### PR TITLE
Wip load interval v2

### PR DESCRIPTION
**Pull request by n1cn0c**
This pull request includes methods to set/modify load_interval on ethernet interfaces, portchannel interfaces and ip interfaces.

### CODE REVIEW

**Comment by devrobo** [comment]
Hi, Did you have any questions? Do you want us to do a code review?

**Comment by n1cn0c** [comment]
Hi John. Please review the code and merge it into your develop branch. After that we would like to contribute even more because we need a few features that are not implemented yet. We've also started to get in touch with Arista Professional Services.

**Comment by devrobo** [comment]
Hi Nick,
We code reviewed the change and were wondering if the change belongs in the BaseInterface class? What was the reason for adding the "module ET_PO_loadinterval"?

Thanks,
John

**Comment by n1cn0c** [comment]
Hi John,

you are right. It does not makes sense to write an own module. I thought load-interval is not needed on a vxlan interface but I checked it and it is configurable. I'll change it and come back to you soon.

Thanks,
Nick

**Comment by n1cn0c** [comment]
Hi John,

I have changed my commits and added the load-interval function in BaseInterfaceClass. Please verify my changes.

Thanks,
Nick

**Comment by devrobo** [comment]
Please test this

**Comment by jerearista** [comment]
CI ran successfully when manually kicked.   I'll debug why it didn't auto-run, separately.

**Pull request merged**
