### PR TITLE
add the ip host function for static dns entries.

### PR DESCRIPTION
**Pull request by mmailand**

### CODE REVIEW

**Comment by jerearista** [comment]
Please change the ipaddress option to a list and change the regexes to capture multiple IP addresses.

**Comment by mmailand** [comment]
Hi, I think I have to change more, because multiple IPs cannot represented by a single string, eg
'2.2.2.2 1.1.1.1 3.3.3.3', because the EOS is sorting the IPs to '1.1.1.1 2.2.2.2 3.3.3.3'
Therefore I think it should be an Array.
And in the puppet-eos module we will sort the user input and send it down to the rbeapi.
Then we should get it idempotent.
Is that the right way?

**Comment by jerearista** [comment]
Yes.  That method works well.

**Comment by mmailand** [comment]
Hi Jere,
I updated the pull request.

**Comment by jerearista** [comment]
Jenkins, test this please

**Pull request merged**
